#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='\[\e[92m\]\u\[\e[90m\]@\[\e[37m\]\H \[\e[38;5;32;1m\]\w \[\e[93m\]($(git branch 2>/dev/null | grep '"'"'*'"'"' | colrm 1 2)) \[\e[39m\]\\$ \[\e[0m\]'
